Removed application.properties
osman-jft/SB_Assign_16_05 pull request #13
Opened 2023-05-31 08:20 UTC by pradeeprawat-jft

2023-05-31 08:28 UTC, jaineetsingh-jft requested changes

2023-05-31 08:28 UTC, jaineetsingh-jft commented on src/main/java/com/example/sb_assign_16_05_23/controller/StudentController.java
> +        if (!sid.equals(student.getId())) {
not required

2023-05-31 08:28 UTC, jaineetsingh-jft commented on src/main/java/com/example/sb_assign_16_05_23/service/impl/StudentServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("Student not found"));
handle error exception

2023-05-31 08:28 UTC, jaineetsingh-jft commented on src/main/java/com/example/sb_assign_16_05_23/service/impl/StudentServiceImpl.java
> +        existingStudent.setMarks(studentData.getMarks());
use modelmapper or beanutils

2023-05-31 08:28 UTC, jaineetsingh-jft commented on src/main/java/com/example/sb_assign_16_05_23/service/impl/StudentServiceImpl.java
> +        double previousMarks = Double.POSITIVE_INFINITY;
use same function as present in develop

2023-05-31 11:59 UTC, pradeeprawat-jft commented on src/main/java/com/example/sb_assign_16_05_23/service/impl/StudentServiceImpl.java
> +        double previousMarks = Double.POSITIVE_INFINITY;
Done

2023-05-31 11:59 UTC, pradeeprawat-jft commented on src/main/java/com/example/sb_assign_16_05_23/service/impl/StudentServiceImpl.java
> +        existingStudent.setMarks(studentData.getMarks());
Done

2023-05-31 12:00 UTC, pradeeprawat-jft commented on src/main/java/com/example/sb_assign_16_05_23/service/impl/StudentServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("Student not found"));
Done

2023-05-31 12:29 UTC, pradeeprawat-jft commented on src/main/java/com/example/sb_assign_16_05_23/controller/StudentController.java
> +        if (!sid.equals(student.getId())) {
removed

2023-06-01 05:46 UTC, pradeeprawat-jft commented on src/main/java/com/example/sb_assign_16_05_23/errors/GlobalExceptionHandling.java
> +            String fieldName = e.getField(); //.split("].", 2)[1]; // "list[0].studentName -> {0: list[0, 1: studentName} [1]-> studentName
prev code is not Working for Single Object of StudentDTO so that's Why had to comment single line of code

2023-06-01 07:02 UTC, jaineetsingh-jft approved these changes

2023-06-01 07:02 UTC, merged